### ISSUE TITLE
Suggestion, use a newer wrapped native contract

### ISSUE THREAD

**Issue by ghost** [DonnyMarbles/DonnySwap#1]
Hi, I saw you are deploying contracts for DonnySwap on PEAQ, may I make a suggestion to use a newer WPEAQ contract? The one you are using(WETH9 based) has some drawbacks related to approval, permit and smart contract interaction.

See audit for WETH contract of Scroll network here:
https://blog.openzeppelin.com/scroll-phase-2-audit#smart-contract-wallets-cannot-withdraw-weth

What they did was to instead use a WrappeEther contract based on openzeppelin ERC20Permit.
https://github.com/scroll-tech/scroll-contracts/blob/main/src/L2/predeploys/WrappedEther.sol

**Comment by DonnyMarbles** [comment]
Hi Foundrywindow999,

I have gone ahead and implemented your suggestion here:
https://peaq.subscan.io/account/0x2998dd50d7bd02bd275e5971274e6c2b03ffe865?tab=contract
Feel free to review it before I proceed any further with re-deploying the
factory, router, DSFO NFT contract & FeeManager

I appreciate your consideration as I'm trying to make DonnySwap's UX as
safe as possible

Cheers,
Donny Marbles

Owner / Founder Better Future Labs LLC
peaq Genesis Node partner & Blockchain Infrastructure Provider

**Comment by ghost** [comment]
Looks good! Closing the issue now.
